### ISSUE TITLE
Ver de adicionar o status do pedido com um botão de "recebi meu pedido" no show de order

### ISSUE THREAD

**Issue by mayaravass** [auab/comidas_regionais_marketplace#30]
Atualizar o modelo, controlle, view e front com a informação de status. 
Colocar um check (botão) que atualiza o status do pedido de em andamento para finalizado.

**Comment by auab** [comment]
cancelado (botao de cancelar o pedido no lugar do lixinho tanto para o comprador quanto o vendedor)
em processamento (default)
finalizado (para o usuario COMPRADOR aparece um botão de recebi meu pedido)
